### ISSUE TITLE
Debug log support for nginx on ARM64

### ISSUE THREAD

**Issue by razvanvirtan** [unikraft/lib-nginx#5]
Currently, nginx is crashing on ARM64 if the debug log is enabled from `fs0/nginx/conf/nginx.conf`.

After looking on the nginx code, I've found out that the`ngx_log_error_core()` function is trying to access memory from `ngx_cached_err_log_time.data` (this is a char pointer). `ngx_cached_err_log_time` is declared in `src/core/ngx_times.c` and it's `data` field (the pointer we need) is modified only by `ngx_time_update()`. This function updates the nginx time cache according to the system timer. However, it seems to modify `ngx_cached_err_log_time.data` only when the number of seconds kept by the nginx cache is different from the one measured by the system timer. Therefore, from moment 0 to moment 1 second, both the nginx cache and the system timer record 0 seconds and our pointer remains NULL, even if `ngx_time_update()` has been called.

On x86, it takes long enough to reach this part of the code where `ngx_cached_err_log_time.data` is needed, so the pointer is already initialized and there is no problem. On ARM64, it seems that this point is reached before 1 second and it generates the crash because of an invalid memory access.

The easiest fix would be to initialize `ngx_cached_err_log_time.data` with `&cached_err_log_time[0][0]`  in `ngx_time_init()` (similar to what is done at update). Still, I thought there could be some issues with the ARM64 generic timer implementation (I've already applied this PR `https://github.com/unikraft/unikraft/pull/175`, but it didn't solve the problem).

**Comment by razvand** [comment]
Solved by #6
